import math

print("Square Root:", math.sqrt(25))
print("Power:", math.pow(2, 3))
print("Factorial:", math.factorial(5))
print("Ceil:", math.ceil(4.3))
print("Floor:", math.floor(4.8))
print("Absolute:", math.fabs(-10))
print("GCD:", math.gcd(12, 18))
print("LCM:", math.lcm(4, 6))
print("Integer Square Root:", math.isqrt(20))
print("Exponential:", math.exp(2))
print("Log:", math.log(10))
print("Log10:", math.log10(100))
print("Sin:", math.sin(math.pi / 2))
print("Cos:", math.cos(0))
print("Tan:", math.tan(0))
print("Degrees:", math.degrees(math.pi))
print("Radians:", math.radians(180))
print("Pi:", math.pi)
print("Euler's Number:", math.e)
print("Copy Sign:", math.copysign(5, -2))