import pandas as pd
data = pd.read_excel(r"D:\DS_AI_Internship\day7\task.xlsx")
print("Original Dataset:")
print(data)
print("\nShape of dataset:")
print(data.shape)
print("\nMissing values in each column:")
print(data.isnull().sum())
print("\nTotal missing values:")
print(data.isnull().sum().sum())
print("\nDuplicate rows:")
print(data[data.duplicated()])
print("\nNumber of duplicate rows:")
print(data.duplicated().sum())
data = data.drop_duplicates()
data["Age"] = data["Age"].fillna(data["Age"].mean()).astype(int)
data["Marks"] = data["Marks"].fillna(data["Marks"].mean()).astype(int)
data["Name"] = data["Name"].fillna("None")
data["City"] = data["City"].fillna("None")
data["Gender"] = data["Gender"].fillna("None")
print("\nCleaned Dataset:")
print(data)
print("\nShape of cleaned dataset:")
print(data.shape)
print(data["Name"])
print(data.iloc[3,4])